### ISSUE TITLE
Miss dependency implement

### ISSUE THREAD

**Issue by phanxuanphucnd** [qute012/Wav2Keyword#2]
Hi @qute012 

What is `from speech_commands.input_data import AudioProcessor` in Line import: https://github.com/qute012/Wav2Keyword/blob/main/downstream_kws.py#L83 ?

Please help me

**Comment by wdjose** [comment]
> Hi @qute012
> 
> What is `from speech_commands.input_data import AudioProcessor` in Line import: https://github.com/qute012/Wav2Keyword/blob/main/downstream_kws.py#L83 ?
> 
> Please help me

Make a copy of the `speech_commands` directory from TensorFlow examples: [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands)
