### ISSUE TITLE
Requirement Issues

### ISSUE THREAD

**Issue by BeardyMan37** [qute012/Wav2Keyword#5]
Hello. I am facing fairseq version issues when trying to replicate your results. Please provide a requirements.txt file to replicate a working environment in which I can verify the results reported in the paper. Thank you.

**Comment by BeardyMan37** [comment]
Managed to resolve it.

**Comment by salmaShahid** [comment]
> Managed to resolve it.

Please share requirement.txt file and I want to reproduce results; i am facing version related issues on colab.
